name = "wesselkvartlet-hjemmeside"
compatibility_date = "2024-08-25"

pages_build_output_dir = "dist"

[build]
command = "npm run build"

[env.preview.vars]
NODE_ENV = "development"

[env.production.vars]
NODE_ENV = "production"